//.github/workflows/sample.yml
name: sol-test-js
on: [push]

jobs:
  run_sample_test_job:
    runs-on: ubuntu-latest
    name: A job to run solidity tests in js
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Custom Fork Test
        uses: EthereumRemix/ts-sol-test@v1.3.46-dev
        with:
          test-path: 'sample/tests/custom/hardFork.test.ts'
          contract-path: 'sample/contracts/custom/mainnet_ens.sol'
          compiler-version: '0.8.17'
          hard-fork: 'merge'
          node-url: 'https://rpc.archivenode.io/e50zmkroshle2e2e50zm0044i7ao04ym'